spring.datasource.url=jdbc:postgresql://fitness-postgres:5432/fitness

spring.jpa.hibernate.ddl-auto=update

management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true