# Application
spring.application.name=fitness-training
spring.profiles.active=local


# Database
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Actuator
management.endpoints.web.base-path=/actuator
management.endpoints.access.default=none
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.access=read-only
management.endpoint.info.access=read-only
management.endpoint.prometheus.access=read-only

management.health.defaults.enabled=true

management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
management.info.process.enabled=true
