# Database
# for Docker Network
spring.datasource.url=jdbc:postgresql://fitness-postgres:5432/fitness

spring.datasource.username=postgres
spring.datasource.password=kljlr804ythf4i1-2u
spring.jpa.hibernate.ddl-auto=update



# Application
app.cors.allowed-origins=



# Security
jwt.response.cookie.secure=true



# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=never
management.endpoint.env.show-values=never